### ISSUE TITLE
Wrong QR code

### ISSUE THREAD

**Issue by xfoldvar** [GloBee-Official/payment-api-php#12]
Hello Globee,
First of all thank you so much for doing payment gate, we really appreciate it. We implemented your gate to our new shop - www.crypto3dhats.com and today we tested the lightning network payment. Unfortunately it didn't work out so I am writing you to get to know if we are doing something wrong or what happened. The QR code that was generated by globee has lower price that was on the invoice, so the payment processor evaluated the payment as underpaid. I am attaching printscreens of eclair wallet, globee payment gate (there is a visible difference in btc amount). Could you please advice why this happened? Also I looked in my globee profile and there is this payment but when I want to refund it I see 0 btc, printscreens also attached. We would love to add LN to our eshop but first we have to test it so we know this underpaid payments won't happen again.
I am attaching 4 printscreens. We are using this SDK for communication with Globee API, but maybe this is not a problem of SDK.
Thank you.

![41420759_269652196987991_7470576534529507328_n](https://user-images.githubusercontent.com/22655981/45269066-8b923680-b487-11e8-9e57-a5790640b0c6.png)
![41427716_2105428046154339_7676285410510635008_n](https://user-images.githubusercontent.com/22655981/45269067-8b923680-b487-11e8-8366-b46382417053.png)
![41585438_249921129047147_3765355544450170880_n](https://user-images.githubusercontent.com/22655981/45269068-8b923680-b487-11e8-8775-a6e6d6e847f4.png)
![41513692_2171674889752908_6629432366706196480_n](https://user-images.githubusercontent.com/22655981/45269069-8b923680-b487-11e8-9c55-a3b481679027.png)

**Comment by Xethron** [comment]
This has been resolved
